/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.base$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.base$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.base$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true
    }
  },
  {
    name: 'about',
    path: '/about',
    component: 'layout.base$view.about',
    meta: {
      title: 'about',
      i18nKey: 'route.about'
    }
  },
  {
    name: 'admin',
    path: '/admin',
    component: 'layout.base$view.admin',
    meta: {
      title: 'admin',
      i18nKey: 'route.admin',
      icon: 'mdi:monitor-dashboard',
      order: 1,
      fixedIndexInTab: 0,
      module: 'admin'
    }
  },
  {
    name: 'disk',
    path: '/disk',
    component: 'layout.base$view.disk',
    meta: {
      title: 'disk',
      i18nKey: 'route.disk',
      icon: 'mdi:harddisk',
      order: 2,
      module: 'disk'
    }
  },
  {
    name: 'favorite',
    path: '/favorite',
    component: 'layout.base$view.favorite',
    meta: {
      title: 'favorite',
      i18nKey: 'route.favorite'
    }
  },
  {
    name: 'group-share',
    path: '/group-share',
    component: 'layout.base$view.group-share',
    meta: {
      title: 'group-share',
      i18nKey: 'route.group-share'
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page'
    }
  },
  {
    name: 'init',
    path: '/init',
    component: 'layout.base$view.init',
    meta: {
      title: 'init',
      i18nKey: 'route.init'
    }
  },
  {
    name: 'log',
    path: '/log',
    component: 'layout.base',
    meta: {
      title: 'log',
      i18nKey: 'route.log'
    },
    children: [
      {
        name: 'log_file',
        path: '/log/file',
        component: 'view.log_file',
        meta: {
          title: 'log_file',
          i18nKey: 'route.log_file'
        }
      },
      {
        name: 'log_login',
        path: '/log/login',
        component: 'view.log_login',
        meta: {
          title: 'log_login',
          i18nKey: 'route.log_login'
        }
      },
      {
        name: 'log_operation',
        path: '/log/operation',
        component: 'view.log_operation',
        meta: {
          title: 'log_operation',
          i18nKey: 'route.log_operation'
        }
      }
    ]
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat|wecom-login)?',
    component: 'layout.base$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true
    }
  },
  {
    name: 'manage',
    path: '/manage',
    component: 'layout.base',
    meta: {
      title: 'manage',
      i18nKey: 'route.manage',
      icon: 'mdi:cog',
      order: 3,
      module: 'admin'
    },
    children: [
      {
        name: 'manage_dept',
        path: '/manage/dept',
        component: 'view.manage_dept',
        meta: {
          title: 'manage_dept',
          i18nKey: 'route.manage_dept',
          icon: 'mdi:office-building',
          order: 4
        }
      },
      {
        name: 'manage_dict',
        path: '/manage/dict',
        component: 'view.manage_dict',
        meta: {
          title: 'manage_dict',
          i18nKey: 'route.manage_dict',
          icon: 'mdi:book-open-variant',
          order: 6
        }
      },
      {
        name: 'manage_menu',
        path: '/manage/menu',
        component: 'view.manage_menu',
        meta: {
          title: 'manage_menu',
          i18nKey: 'route.manage_menu',
          icon: 'mdi:menu',
          order: 3
        }
      },
      {
        name: 'manage_notice',
        path: '/manage/notice',
        component: 'view.manage_notice',
        meta: {
          title: 'manage_notice',
          i18nKey: 'route.manage_notice'
        }
      },
      {
        name: 'manage_post',
        path: '/manage/post',
        component: 'view.manage_post',
        meta: {
          title: 'manage_post',
          i18nKey: 'route.manage_post',
          icon: 'mdi:briefcase',
          order: 5
        }
      },
      {
        name: 'manage_role',
        path: '/manage/role',
        component: 'view.manage_role',
        meta: {
          title: 'manage_role',
          i18nKey: 'route.manage_role',
          icon: 'mdi:account-group',
          order: 2
        }
      },
      {
        name: 'manage_settings',
        path: '/manage/settings',
        component: 'view.manage_settings',
        meta: {
          title: 'manage_settings',
          i18nKey: 'route.manage_settings',
          icon: 'mdi:cog-outline',
          order: 8
        }
      },
      {
        name: 'manage_storage',
        path: '/manage/storage',
        component: 'view.manage_storage',
        meta: {
          title: 'manage_storage',
          i18nKey: 'route.manage_storage'
        }
      },
      {
        name: 'manage_user',
        path: '/manage/user',
        component: 'view.manage_user',
        meta: {
          title: 'manage_user',
          i18nKey: 'route.manage_user',
          icon: 'mdi:account',
          order: 1
        }
      }
    ]
  },
  {
    name: 'my-share',
    path: '/my-share',
    component: 'layout.base$view.my-share',
    meta: {
      title: 'my-share',
      i18nKey: 'route.my-share'
    }
  },
  {
    name: 'notice-user',
    path: '/notice-user',
    component: 'layout.base$view.notice-user',
    meta: {
      title: 'notice-user',
      i18nKey: 'route.notice-user'
    }
  },
  {
    name: 'recent',
    path: '/recent',
    component: 'layout.base$view.recent',
    meta: {
      title: 'recent',
      i18nKey: 'route.recent'
    }
  },
  {
    name: 'server',
    path: '/server',
    component: 'layout.base$view.server',
    meta: {
      title: 'server',
      i18nKey: 'route.server',
      icon: 'mdi:view-dashboard-outline',
      order: 5,
      fixedIndexInTab: 0,
      module: 'server'
    }
  },
  {
    name: 'server-manage',
    path: '/server-manage',
    component: 'layout.base',
    meta: {
      title: 'server-manage',
      i18nKey: 'route.server-manage',
      icon: 'mdi:server-network',
      order: 6,
      module: 'server'
    },
    children: [
      {
        name: 'server-manage_monitor',
        path: '/server-manage/monitor',
        component: 'view.server-manage_monitor',
        meta: {
          title: 'server-manage_monitor',
          i18nKey: 'route.server-manage_monitor',
          icon: 'mdi:monitor-eye',
          order: 1
        }
      },
      {
        name: 'server-manage_server-detail',
        path: '/server-manage/server-detail',
        component: 'view.server-manage_server-detail',
        meta: {
          title: 'server-manage_server-detail',
          i18nKey: 'route.server-manage_server-detail',
          icon: 'mdi:server-outline',
          order: 3
        }
      },
      {
        name: 'server-manage_server-list',
        path: '/server-manage/server-list',
        component: 'view.server-manage_server-list',
        meta: {
          title: 'server-manage_server-list',
          i18nKey: 'route.server-manage_server-list',
          icon: 'mdi:server',
          order: 2
        }
      }
    ]
  },
  {
    name: 'share',
    path: '/share',
    component: 'layout.base$view.share',
    meta: {
      title: 'share',
      i18nKey: 'route.share'
    }
  },
  {
    name: 'shared-with-me',
    path: '/shared-with-me',
    component: 'layout.base$view.shared-with-me',
    meta: {
      title: 'shared-with-me',
      i18nKey: 'route.shared-with-me'
    }
  },
  {
    name: 'trash',
    path: '/trash',
    component: 'layout.base$view.trash',
    meta: {
      title: 'trash',
      i18nKey: 'route.trash'
    }
  },
  {
    name: 'user-center',
    path: '/user-center',
    component: 'layout.base$view.user-center',
    meta: {
      title: 'user-center',
      i18nKey: 'route.user-center'
    }
  }
];
