import type { ElegantConstRoute, ElegantRoute } from '@elegant-router/types';
import type { RouteModule } from '@/typings/router';
import { generatedRoutes } from '../elegant/routes';
import { layouts, views } from '../elegant/imports';
import { transformElegantRoutesToVueRoutes } from '../elegant/transform';
import { generateSharedRoutes, SHARED_PAGE_CONFIGS, expandAutoLayoutRoutes } from './shared-pages';
import AutoLayout from '@/layouts/auto-layout/index.vue';

/**
 * Shared page view names that are handled by generateSharedRoutes.
 * These routes in generatedRoutes (from elegant-router) use root paths (e.g. /user-center)
 * that don't match module-specific navigation (e.g. /admin/user-center).
 * They must be excluded from generatedRoutes to avoid 404 conflicts and redundancy.
 */
const SHARED_PAGE_VIEW_NAMES = SHARED_PAGE_CONFIGS.map(config => config.viewName);

// Extend auto-generated layouts with auto layout (not generated by elegant-router)
// Lazy-init to avoid circular dependency with shared-pages → imports
function getLayoutsWithAuto() {
  return {
    ...layouts,
    auto: AutoLayout
  };
}

/**
 * 指定路由使用的 layout（覆盖默认的 base layout）
 * key: 路由名称, value: layout 名称
 */
const routeLayoutMap: Record<string, string> = {
  login: "blank",
  '403': 'blank',
  '404': 'blank',
  '500': 'blank',
  init: 'blank',
  disk: 'disk'
};

/**
 * 指定路由所属的模块
 * 用于菜单按模块过滤显示
 * - admin: 管理中心模块（admin、manage 等页面）
 * - disk: 网盘模块（disk 页面）
 */
const routeModuleMap: Record<string, RouteModule> = {
  manage: 'admin',
  manage_user: 'admin',
  manage_role: 'admin',
  manage_menu: 'admin',
  manage_dept: 'admin',
  manage_post: 'admin',
  manage_dict: 'admin',
  manage_log: 'admin',
  manage_log_operation: 'admin',
  manage_log_login: 'admin',
  manage_storage: 'admin',
  manage_settings: 'admin',
  // 网盘模块页面（静态模式下补齐 module，与动态模式后端下发的 meta.module 一致，
  // 使菜单隔离与 workbench 预设在两种模式下表现统一）
  disk: 'disk',
  recent: 'disk',
  favorite: 'disk',
  'my-share': 'disk',
  'shared-with-me': 'disk',
  'group-share': 'disk',
  trash: 'disk',
  // 服务器管理模块页面（静态模式下补齐 module，使菜单按 server 模块隔离）
  server: 'server',
  'server-manage': 'server',
  'server-manage_monitor': 'server',
  'server-manage_server-list': 'server',
  'server-manage_server-detail': 'server',
  // 网关模块
  gateway: 'gateway'
};

/**
 * 转换路由的 layout
 * elegant-router 默认所有路由使用 base layout，这里支持为特定路由指定不同的 layout
 */
function transformRouteLayout(routes: ElegantConstRoute[]): ElegantConstRoute[] {
  return routes.map(route => {
    const newRoute = { ...route } as ElegantConstRoute;
    const layoutName = routeLayoutMap[newRoute.name];

    if (layoutName && newRoute.component) {
      // 将 layout.base$view.xxx 转换为 layout.disk$view.xxx
      newRoute.component = newRoute.component.replace(/^layout\.[^$]+/, `layout.${layoutName}`) as ElegantConstRoute['component'];
    }

    // 添加 module 配置
    const moduleName = routeModuleMap[newRoute.name];
    if (moduleName && newRoute.meta) {
      newRoute.meta.module = moduleName;
    }

    if (newRoute.children) {
      newRoute.children = transformRouteLayout(newRoute.children);
    }

    return newRoute;
  });
}

/** create routes when the auth route mode is static */
export function createStaticRoutes() {
  const constantRoutes: ElegantRoute[] = [];

  const authRoutes: ElegantRoute[] = [];

  // Generate shared page routes from the registry (module-specific paths like /admin/user-center)
  const sharedRoutes = generateSharedRoutes(SHARED_PAGE_CONFIGS);

  // Filter out routes from generatedRoutes that are covered by shared pages
  // (elegant-router generates root-path routes like /user-center, but shared pages
  // generate module-specific routes like /admin/user-center — the root-path ones
  // conflict with module navigation and must be excluded)
  const filteredGeneratedRoutes = generatedRoutes.filter(
    route => !SHARED_PAGE_VIEW_NAMES.includes(route.name as string)
  );

  // 转换路由 layout 和 module
  const transformedRoutes = transformRouteLayout(filteredGeneratedRoutes);

  [...sharedRoutes, ...transformedRoutes].forEach(item => {
    if (item.meta?.constant) {
      constantRoutes.push(item as ElegantRoute);
    } else {
      authRoutes.push(item as ElegantRoute);
    }
  });

  return {
    constantRoutes,
    authRoutes
  };
}

/**
 * Get auth vue routes
 *
 * Expands layout.auto routes into module-specific variants before transformation.
 *
 * @param routes Elegant routes
 */
export function getAuthVueRoutes(routes: ElegantConstRoute[]) {
  const expanded = expandAutoLayoutRoutes(routes);
  return transformElegantRoutesToVueRoutes(expanded, getLayoutsWithAuto(), views);
}